### ISSUE TITLE
parameters and flops

### ISSUE THREAD

**Issue by MSKBOX** [THU-MIG/yolov10#13]
I've noticed an issue; the parameter count for yolov10n is 2,708,210, with 8.4 GFLOPs of floating-point operations. This differs from the numbers in the paper. I wonder if it's a calculation issue on my end?

**Comment by MSKBOX** [comment]
> Thanks for your interest! It seems that you also count the params and flops of the one-to-many head. Due to that the one-to-many head is not needed during inference, this part of params and FLOPs can be ignored.
> 
> > I've noticed an issue; the parameter count for yolov10n is 2,708,210, with 8.4 GFLOPs of floating-point operations. This differs from the numbers in the paper. I wonder if it's a calculation issue on my end?

Thank you very much, I see

**Comment by Hy87380510** [comment]
Thanks for your guidance. In order to fine-tune my experimental setup, I needed to understand how to implement the following modifications at the code level:

Parameter modification at the code level: How should I identify and exclude parameters in the one-to-many head part in the code?

Code adjustments for FLOPs calculation: What code segments should I modify to ensure that one-to-many heads are excluded when calculating FLOPs?

Looking forward to your specific guidance.

Thanks!

**Comment by jameslahm** [comment]
Could you please try to delete the `self.cv2` and `self.cv3` in `v10Detect`, and also comment the forward of one-to-many head?

**Comment by Hy87380510** [comment]
Thanks for your previous reply. I ran into some technical difficulties while trying to make modifications to self.cv2 and self.cv3 in v10Detect. The specific error information is as follows:
![image](https://github.com/THU-MIG/yolov10/assets/157335035/c0823fa8-88cf-4b6e-8a9a-e0f74a984a29)

![image](https://github.com/THU-MIG/yolov10/assets/157335035/bab021b2-338d-4890-975f-f466fc7b7fe8)


In order to solve this problem and continue my experiment, I really need your help. Could you please provide some more detailed information or guidance to help me understand and correct this error?

Thank you very much for your time and support.

**Comment by jameslahm** [comment]
Thanks. Could you please try to delete the self.cv2 and self.cv3 and comment the forward of one-to-many head rather than self.one2one_cv2, self.one2one_cv3 and the forward of one-to-one head?

**Comment by Hy87380510** [comment]
I want to thank you for your previous guidance and help. I tried commenting the code based on your suggestion, but unfortunately the problem I'm having is still not resolved.

Could you help further in order to be able to make the required modifications more precisely? If possible, please indicate the specific code line number that needs to be commented or modified, or if it is convenient for you, provide a relevant code example that has already been commented.

**Comment by jameslahm** [comment]
@Hy87380510 We provide a [script](https://github.com/THU-MIG/yolov10/blob/main/flops.py) to calculate the params and FLOPs correctly in #178. Does that help?
> I want to thank you for your previous guidance and help. I tried commenting the code based on your suggestion, but unfortunately the problem I'm having is still not resolved.
> 
> Could you help further in order to be able to make the required modifications more precisely? If possible, please indicate the specific code line number that needs to be commented or modified, or if it is convenient for you, provide a relevant code example that has already been commented.
