### ISSUE TITLE
📝 Add Hugging Face Demo and Model Pages to README

### ISSUE THREAD

**Issue by kadirnar** [THU-MIG/yolov10#24]
HuggingFace Demo(Zero A100): https://huggingface.co/spaces/kadirnar/Yolov10

HuggingFace Model Page: https://huggingface.co/kadirnar/Yolov10

Colab Demo: https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolov10-object-detection-on-custom-dataset.ipynb  Thanks @SkalskiP

**Comment by jameslahm** [comment]
Thank you very much! We have updated README.

**Comment by jameslahm** [comment]
@kadirnar Thanks for your great efforts! We identify a bug in the HuggingFace demo. https://github.com/THU-MIG/yolov10/issues/100#issuecomment-2136440517. Could you please fix this issue in the HuggingFace demo? We'd appreciate it very much. Thank you!

**Comment by jameslahm** [comment]
@kadirnar Thanks for your great efforts! We found that the prediction results are not the same in our local environment and the HuggingFace demo. After investigation, we found that this is caused by the incorrect input format. As shown in the document for `prediction`:
https://github.com/THU-MIG/yolov10/blob/main/docs/en/modes/predict.md#inference-sources
![image](https://github.com/THU-MIG/yolov10/assets/43805318/e7fa3a43-2974-45fa-b9a3-d52827ea4c54)

For the `numpy.array` input, the model expects the input with the format of `BGR`. However, the `gr.Image(type='numpy')` component will output the `numpy.array` with the format of `RGB`, which results in the incorrect predictions. Replacing `gr.Image(type="numpy", label="Image")` with `gr.Image(type="pil", label="Image")` can address this issue by passing the correct `PIL` format with `RGB`. Could you please fix this issue in the HuggingFace demo? We'd appreciate it very much. Thank you!

**Comment by kadirnar** [comment]
I fixed it. Thank you for the detailed explanation ❤️

**Comment by jameslahm** [comment]
@kadirnar Thanks for your efforts! But you seem to have changed it in the wrong place. Could you please replace `gr.Image(type="numpy", label="Image")` in this line https://huggingface.co/spaces/kadirnar/Yolov10/blob/main/app.py#L52 with 
`gr.Image(type="pil", label="Image")`. Thanks a lot!

> I fixed it. Thank you for the detailed explanation ❤️

**Comment by kadirnar** [comment]
Sorry😅 I fixed it.

**Comment by jameslahm** [comment]
@kadirnar Thanks a lot for your help! It works now! ❤️
