### ISSUE TITLE
ONNX weights + web demo

### ISSUE THREAD

**Issue by xenova** [THU-MIG/yolov10#26]
Hi there! 👋 I've converted the models to ONNX and uploaded them to the Hugging Face Hub ([link](https://huggingface.co/models?other=yolov10&library=onnx)):
- https://huggingface.co/onnx-community/yolov10s
- https://huggingface.co/onnx-community/yolov10b
- https://huggingface.co/onnx-community/yolov10m
- https://huggingface.co/onnx-community/yolov10n
- https://huggingface.co/onnx-community/yolov10l
- https://huggingface.co/onnx-community/yolov10x

In each model card, I also added usage instructions for [Transformers.js](https://huggingface.co/docs/transformers.js), a JavaScript library which allows you to run the models in the browser. You can try out the web demo here: https://huggingface.co/spaces/Xenova/yolov10-web

![yolov10-web](https://github.com/THU-MIG/yolov10/assets/26504141/d9cfd8b5-2cc7-4d42-ab7f-b21722934df7)

**Comment by jameslahm** [comment]
Thank you very much! We have updated README to highlight the onnx weights and the web demo.

**Comment by jameslahm** [comment]
@xenova Thanks for your great efforts! We identify a bug in the HuggingFace demo. https://github.com/THU-MIG/yolov10/issues/100#issuecomment-2136440517. Could you please check and fix this issue in the HuggingFace demo? We'd appreciate it very much. Thank you!

**Comment by jameslahm** [comment]
@xenova Thanks for your great efforts! We found there are some differences between the predicted results in our local environment and in the huggingface demo. Here is a minimal example for reproducing this.
```
yolo export model=yolov10s.pt format=onnx opset=13 simplify
wget https://skalskip-yolo-arena.hf.space/file=/tmp/gradio/56eee51b0a661453cbf915229dfbadc00b7a0cad/vehicles.png
yolo predict model=yolov10s.onnx source=vehicles.png conf=0.25
```
The result in our local environment is below
![vehicles](https://github.com/THU-MIG/yolov10/assets/43805318/21317d2f-388c-4b2f-a26d-cd0256d69d7c)
However, the result in the HuggingFace demo is different
![image](https://github.com/THU-MIG/yolov10/assets/43805318/f0ce7f31-339e-4100-bb00-4422d3a40efa)

We found the same issue in #24, which is caused by the incorrect input format. But for this HuggingFace demo with [Transformers.js](https://huggingface.co/docs/transformers.js), we have not identified the root cause. May we ask for your help? We'd appreciate it very much. Thanks a lot!

**Comment by xenova** [comment]
Good spot! I simply hadn't accounted for BGR vs RGB. Will fix!

**Comment by xenova** [comment]
I've [updated the preprocessor_config.json](https://huggingface.co/onnx-community/yolov10s/blob/d2e77c459809b1a4ba599f837f6aed7c5c42d377/preprocessor_config.json#L2) accordingly for each model, which will fix the RGB -> BGR conversion without any code changes necessary from users.

I've also updated the demo to use the [`m` variant](https://huggingface.co/onnx-community/yolov10m) as it produces better results when quantized (important for web users).

![image](https://github.com/THU-MIG/yolov10/assets/26504141/eada004c-45e1-4c31-8727-0c809654d970)


I tested on the image sent above, and I get the same as the python version (with one inaccuracy: truck -> car)
![image](https://github.com/THU-MIG/yolov10/assets/26504141/2e732763-bd35-4adc-8f96-502b8c8e7a39)

**Comment by jameslahm** [comment]
@xenova Thanks a lot for your great efforts! However, we find that the results between our local environment and the HuggingFace demo is still different. Specifically, we fork your fantastic demo here and we change the `quantized` to `false`. Then we upload the above image and the result is below
![image](https://github.com/THU-MIG/yolov10/assets/43805318/6dd6b9ff-17e7-45fb-9418-00c600c7ba5e)

Then, we use the same `yolov10m.onnx` to predict the above image in our local environment with the following steps
```
yolo export model=yolov10m.pt format=onnx opset=13 simplify
yolo predict model=yolov10m.onnx source=vehicles.png conf=0.2
```
And the result is below
![vehicles-yolov10m](https://github.com/THU-MIG/yolov10/assets/43805318/cffc9f77-db0b-4d9d-a1d8-92fd8d533141)
It is different from the result in the HuggingFace demo.

Could you please take a look? We'd appreciate it very much. Thanks a lot!

**Comment by jameslahm** [comment]
@xenova We further investigated this and found that the reason may not be the input format in this HuggingFace demo. For onnx model, it's input format is `RGB`, as shown in https://github.com/THU-MIG/yolov10/blob/8f0984817da455e4dd14c2281d669e04fdafee7d/ultralytics/engine/predictor.py#L123-L127
Therefore, the input format in the original HuggingFace model is correct. We found a similar issue regarding the different prediction results in https://github.com/THU-MIG/yolov10/issues/100#issuecomment-2137912794, which is accounted for different preprocessing step in Roboflow inference. Could the reason here be due to the different preprocessing in Transformers.js? Thanks a lot!

**Comment by xenova** [comment]
I have reverted the RGB -> BGR update and also tested on a [square image](https://github.com/THU-MIG/yolov10/assets/26504141/00ef6590-2966-4b8f-9f26-f598f644438b), and the results seem good:


![image](https://github.com/THU-MIG/yolov10/assets/26504141/1e87c09b-92df-4ec4-be4c-66b64c4f266b)

As pointed out [here](https://github.com/THU-MIG/yolov10/issues/100#issuecomment-2137912794), a significant difference in pre-processing seems to be causing these issues. Further investigation suggests [letterboxing](https://github.com/THU-MIG/yolov10/blob/8f0984817da455e4dd14c2281d669e04fdafee7d/ultralytics/engine/predictor.py#L155-L156) with padding should be applied instead of simply resizing.

**Comment by xenova** [comment]
Letterboxing seems to have fixed this!
![image](https://github.com/THU-MIG/yolov10/assets/26504141/fe12ac89-89a3-40da-bbed-3c9ce510eafe)

**Comment by jameslahm** [comment]
@xenova Thanks a lot for your great efforts! But we test the above image in the HuggingFace demo and the result is below, which is different from yours. Do we miss something?
![image](https://github.com/THU-MIG/yolov10/assets/43805318/4fbde20f-6ddb-4a23-84f8-4862d3d0920f)

**Comment by jameslahm** [comment]
@xenova Thanks! We cleared the cache by refreshing the page with disabling the cache in devtool. We then test your image in the demo and the result is below. Strangely, the result is still different from yours.
![image](https://github.com/THU-MIG/yolov10/assets/43805318/9e4606bb-f879-42bc-a22b-2604cf7e2034)

**Comment by xenova** [comment]
> We cleared the cache by refreshing the page with disabling the cache in devtool.

You also need to clear the cached model files as follows:

1. Open devtools
2. Go to "Application" tab
3. Go to "Storage" -> "Cache storage"
4. Right click "transformers-cache" and click "Delete".

You can also try in an incognito tab or new browser.

**Comment by jameslahm** [comment]
@xenova Thanks a lot for your detailed explanation and great help! It works now! Thank you very much! ❤️
![image](https://github.com/THU-MIG/yolov10/assets/43805318/5041785c-9fd5-4bf3-9125-13b24c50696b)
