### ISSUE TITLE
openvino

### ISSUE THREAD

**Issue by taotaoland** [THU-MIG/yolov10#89]
can the pt model transformed to openvino model?

**Comment by jameslahm** [comment]
Thanks for your interest! Does this issue #95 help?

**Comment by rhelck** [comment]
Hey I found the notebook and was able to run it on Intel chips, but when I ran this on aarch64 I got this error

RuntimeError: Exception from src/inference/src/cpp/infer_request.cpp:223:
in reduce_op src/core/NEON/kernels/NEReductionOperationKernel.cpp:1702: Not supported

Not sure if this is due to my environment

**Comment by jameslahm** [comment]
Thanks. It seems like an issue of OpenVINO. Would you mind opening an issue in the repo of the notebook?

**Comment by knoppmyth** [comment]
@rhelck Intel's release of OpenVINO only officially works on Intel hardware. There is an ARM plugin. You can find more info here:
https://docs.openvino.ai/2022.3/openvino_docs_OV_UG_supported_plugins_Supported_Devices.html

**Comment by rhelck** [comment]
I'll open this issue with them, it's got to be unrelated to you YOLO
